id: P010384
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W10919
  title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་ཆོས་མངོན་རྒྱ་མཚོའི་སྙིང་པོ
  author: ''
  volumes:
    9afae5911302469c967a0e3a16ee2c50:
      image_group_id: I00KG04027
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
